### ISSUE TITLE
support json input for det_file

### ISSUE THREAD

**Issue by minooei** [Chien-Hung/DetVisGUI#3] opened 2020-12-24 16:30 UTC
I'm trying to visualize some detector's output but I have only the standard coco json output of the detector, not the pkl file.
I think we can add support for that in the get_det_results method?

**Comment by Chien-Hung** [comment] 2021-01-02 04:32
OK, I will try to support this in these day.

**Comment by Chien-Hung** [comment] 2021-01-05 12:50
Hi, I make DetVisGUI support coco json output format for det_file. 
You can test it. If there are no problem, I would close this issue.

**Comment by minouei-kl** [comment] 2021-01-05 14:05
Awesome!
I test it and it is working as intended.
thanks again.

**Closed as completed** 2021-01-06 10:10 UTC
